#!/bin/sh


empty() {
    if [ -n "$1" ]; then
        if [ -n "$2" ]; then
            return 0
        else
            echo "$2 is empty!!"
            return 1
        fi
    else
        echo "$1 is empty!!"
        return 1
    fi
}
file_extension_check() {
    if [[ "$1" =~ .*.md$ ]]; then
            if [[ "$2" =~ .*.tex ]]; then
                return 0
            else
                echo "$2 isn't matched .*.tex"
                return 1
        fi
    else
        echo "$1 isn't matched .*.md"
        return 1
    fi
}
execution_command() {
    pandoc $1  -o $2 --latex-engine=lualatex -H header.tex 
    sed -i -e '1,50d' $2
    nkf -We -Lm --overwrite $2
}
if empty "$1" "$2"; then
    if file_extension_check "$1" "$2"; then
        execution_command "$1" "$2";
    fi
fi

